workspace:
  base: /data
  path: src/github.com/liu1536326836/drone_test

pipeline:
  build:
    image: golang
    commands:
      - go build
      - go test

clone:
  git:
    image: plugins/git

branches: master
